version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    image: sipacid/grade-notifier:latest
    volumes:
      - ./database:/database
    environment:
      EMAIL: ${EMAIL}
      PASSWORD: ${PASSWORD}
      WEBHOOK_URL: ${WEBHOOK_URL}