services:
  bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    volumes:
      - ./database:/database
    environment:
      EMAIL: ${EMAIL}
      PASSWORD: ${PASSWORD}
      WEBHOOK_URL: ${WEBHOOK_URL}